# Define environment
dist: xenial # Ubuntu 16.04
langauge: bash

# Export variables
env:
  - tf_version=0.12.19 tf_init_cli_options="-input=false" tf_validation_cli_options="" tf_plan_cli_options="-lock=false -input=false -var-file=ams3.tfvars" tf_apply_cli_options="-auto-approve -input=false -var-file=ams3.tfvars"

# Only build pushes to master branch
branches:
  only:
    - main

# Install dependencies
before_install:
  - wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
  - unzip terraform_"$tf_version"_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_"$tf_version"_linux_amd64.zip